#Makefile:

all: 
	cd src; make
clean:
	cd src; make clean
test:
	cd src; make test
tar:
	gtar cvzf Chess_V1.0_src.tar.gz ./README ./COPYRIGHT ./INSTALL ./Makefile ./bin ./doc ./src  
	gtar cvzf Chess_V1.0.tar.gz ./README ./COPYRIGHT ./INSTALL ./bin ./Team7UserManual.pdf
